name: Lint GitHub Actions Workflows

on:
  push:
    paths:
      - ".github/workflows/**"
  pull_request:
    paths:
      - ".github/workflows/**"

jobs:
  lint:
    name: Run actionlint
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run actionlint
        uses: rhysd/actionlint@v1
