name: Lint GitHub Actions Workflows (Windows)

on:
    pull_request:
        push:
              branches:
                      - main

              jobs:
                  lint:
                        runs-on: windows-latest
                            steps:
                                    - name: Checkout repository
                                            uses: actions/checkout@v4

                                                  - name: Download actionlint for Windows
                                                          run: |
                                                                      Invoke-WebRequest -Uri https://github.com/rhysd/actionlint/releases/latest/download/actionlint_1.6.26_windows_amd64.zip -OutFile actionlint.zip
                                                                                Expand-Archive actionlint.zip -DestinationPath actionlint
                                                                                          Move-Item actionlint\actionlint.exe C:\Windows\System32\actionlint.exe

                                                                                                - name: Run actionlint
                                                                                                        run: actionlint.exe

