version: 2
updates:
  # 1️⃣ Update GitHub Actions in workflows
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"  # <-- correct path to your workflows
    schedule:
      interval: "weekly"  # options: "daily", "weekly", "monthly"
    commit-message:
      prefix: "chore"

  # 2️⃣ Optional: Update Terraform providers
  - package-ecosystem: "terraform"
    directory: "terraform"  # <-- path to your Terraform configuration
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
