name: PR Janitor

on:
    schedule:
          - cron: '0 0 * * 0'  # weekly
            workflow_dispatch:

              jobs:
                  close-stale-prs:
                        runs-on: ubuntu-latest
                            steps:
                                    - uses: actions/checkout@v3
                                          - name: Close stale PRs
                                                  uses: actions/stale@v6
                                                          with:
                                                                      repo-token: ${{ secrets.GITHUB_TOKEN }}
                                                                                stale-pr-message: "This PR has been automatically marked as stale."
                                                                                          days-before-stale: 14
                                                                                                    days-before-close: 7

