name: PR Standards

on:
    pull_request:
          types: [opened, edited, synchronize]

          jobs:
              check-pr:
                    runs-on: ubuntu-latest
                        steps:
                                - uses: actions/checkout@v3
                                      - name: Check PR title
                                              run: |
                                                          if [[ ! "${{ github.event.pull_request.title }}" =~ ^(feat|fix|chore|docs|test)/ ]]; then
                                                                      echo "PR title must start with feat/, fix/, chore/, docs/, or test/"
                                                                                  exit 1
                                                                                            fi
                                                                                                  - name: Check PR body
                                                                                                          run: |
                                                                                                                      if [ -z "${{ github.event.pull_request.body }}" ]; then
                                                                                                                                  echo "PR body cannot be empty"
                                                                                                                                              exit 1
                                                                                                                                                        fi

