name: Terraform CI

on:
    pull_request:
          paths:
                  - 'terraform/**'

          jobs:
              fmt:
                    runs-on: ubuntu-latest
                        steps:
                                - uses: actions/checkout@v3
                                      - name: Setup Terraform
                                              uses: hashicorp/setup-terraform@v2
                                                      with:
                                                                  terraform_version: 1.5.0
                                                                        - name: Terraform fmt check
                                                                                run: terraform -chdir=terraform fmt -check
                                                                                      - name: Terraform validate
                                                                                              run: terraform -chdir=terraform validate

