name: Terraform CI/CD Auto-Apply

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  plan-and-apply:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform -chdir=terraform init
        shell: powershell

      - name: Terraform Validate
        run: terraform -chdir=terraform validate
        shell: powershell

      - name: Terraform Plan
        run: terraform -chdir=terraform plan -out=tfplan
        shell: powershell

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve tfplan
        shell: powershell
