name: Terraform CI/CD Auto-Apply

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main  # Automatically applies changes when merged to main

jobs:
  plan:
    runs-on: [self-hosted, windows]

    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID:       ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET:   ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID:       ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        shell: powershell
        run: terraform -chdir=terraform init

      - name: Terraform Validate
        shell: powershell
        run: terraform -chdir=terraform validate

      - name: Terraform Plan
        shell: powershell
        run: terraform -chdir=terraform plan -out=terraform/tfplan

      - name: List Terraform folder (debug)
        shell: powershell
        run: dir terraform

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: terraform/tfplan

  auto-apply:
    runs-on: [self-hosted, windows]
    needs: plan
    if: github.ref == 'refs/heads/main'  # Only auto-apply on main branch push

    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID:       ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET:   ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID:       ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: terraform

      - name: Verify Terraform Plan Exists (debug)
        shell: powershell
        run: dir terraform

      - name: Terraform Apply
        shell: powershell
        run: terraform -chdir=terraform apply -auto-approve terraform/tfplan
