name: Terraform Lint

on:
  workflow_dispatch:   # manual trigger

jobs:
  terraform-lint:
    runs-on: [self-hosted, windows]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      - name: Terraform Init
        run: terraform -chdir=terraform init
      - name: Terraform Validate
        run: terraform -chdir=terraform validate
      - name: Terraform Linter (tflint)
        run: tflint
